### ISSUE TITLE
Project setup: test data

### ISSUE THREAD

**Issue by oandregal** [Vizzuality/iom#1]
I'm trying to run a local version of iom project in order to test what it does (and how it does it). Following the instructions at README, I've had some problems with seeding the database while executing `rake --trace db:setup`

See log here: https://gist.github.com/amaneiro/5877372

**Comment by oandregal** [comment]
As a side note: due to the fact that [db/schema.rb](https://github.com/Vizzuality/iom/blob/development/db/schema.rb) does not reflect properly the final state of the DB after all the migrations, the result of `rake db:schema:load` is quite different than `rake db:migrate`. The first creates more tables (for ex: organizations2) and have some errors with array data types (for example: regions_ids in table data_denormalization should be `integer []`).

**Comment by fraserxu** [comment]
Hi @amaneiro , I'm also trying to set up a local version on my machine. All done except the data set. I'm mainly developing on nodejs and now new to ruby and ror and also don't have any experience setting up the pg database.
Can you write some instructions on setting the data set here? Thanks a lot!

**Comment by oandregal** [comment]
@fraserxu clone the repo, apply the pull request #3 and follow straight the instructions at [README](https://github.com/Vizzuality/iom/blob/development/README) file. That shall make it. If you are wondering around RoR and pg, check the superb http://guides.rubyonrails.org/v3.2.13/

**Comment by fraserxu** [comment]
Cool, thanks @amaneiro . I'm a lazy guy, I'll just clone your code instead of this one. Aha.
